let interactive = ref false
let trace = ref false
let unchecked = ref false
let print_sig = ref false
let dry = ref false
let width = ref 80
let harness = ref true
let inst_limit = ref (-1)
let output = ref "output"
let simplify = ref true
let timeout = ref 895
let concrete = ref false
let static = ref false
let queries = ref false
let policy = ref "breadth"
let encoding = ref "incremental"
let memory = ref "map"
let hashtbl_default_size = 128
