let interactive = ref false
let trace = ref false
let unchecked = ref false
let print_sig = ref false
let dry = ref false
let width = ref 80
let harness = ref true
let output = ref "output"
let simplify = ref true
let timeout = ref 895
let concrete = ref false
let static = ref false
let queries = ref false
let policy = ref "breadth"
let encoding = ref "incremental"
let memory = ref "map"
let budget = 10000
let hashtbl_default_size = 128
let fixed_numbers = ref [ 0; 1; 2; 4; 8; 256; 4096 ]
