(module
  (type $0 (func))
  (type $1 (func (result i32)))
  
  (func $main (type $0)
        (local i32)
        (i32.const 1024)
        (i32.symbolic)
        (local.tee 0)
        (i32.const 0)
        (i32.lt_s)
        (print_stack)
        (sym_assume)
        (print_stack)
        (local.get 0)
        (print_stack)
        (i32.const -100)
        (i32.le_s)
        (print_stack)
        (if
          (then
            (local.get 0)
            (i32.const 1)
            (i32.add)
            (local.set 0))
          (else
            (local.get 0)
            (i32.const 1)
            (i32.sub)
            (local.set 0)))
        (local.get 0)
        (print_stack)
        (i32.const 1)
        (i32.ne)
        (print_stack)
        (sym_assert))
  (memory $0 1)
  (global $0 (mut i32) (i32.const 66592))
  (export "main" (func $main))
  (data $0 (i32.const 1024) "x\00y\00z\00"))
(invoke "main")
