(module
  (type $0 (func))
  (type $1 (func (result i32)))
  (func $main (type $1)
      (local i32)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (nop)
      (i32.const 2048)
      (i32.const 1024)
      (print_stack)
      (local.set 0))
  (memory $0 1)
  (export "main" (func $main)))
